### ISSUE TITLE
Add support for "service-less" badges

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-badger#1]
http://localhost:8089/api/1.0/badge currently gives

```json
{

    "type": [
        "executable",
        "peerreview",
        "licence",
        "spatial",
        "releasetime"
    ],
    "services": [
        "o2r",
        "doaj",
        "crossref"
    ]
}
```

So different services can be used for different badges. The use does not know, which service+badge - combination will yield a result. That is not nice. Ideally, the user should not care about the service but only about the badge!

Therefore **update the API** to not require the services, but instead internally map from badge type to a suitable service. In case multiple services can provide information for a badge, we internally choose the "better" one (i.e. the one that is not N/A), or a "preferred" one if two differing results are obtained.

For transparency, a `?all_services` could be appended and return a JSON providing all the different labels...

**Comment by LukasLohoff** [comment]
The API was updated with #2, can be closed now.
