### ISSUE TITLE
Add Piwik tracker 

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-badger#11]
Add tracking of API calls based on Piwik (we have a Piwik instance running)

- ~~[ ] add docs or script to run piwik locally in a server for testing~~
- [x] evaluate npm packages vs. express middleware
  - https://www.npmjs.com/package/piwik
  - https://www.npmjs.com/package/piwik-tracker
  - app level express middleware, see https://piwik.org/blog/2014/06/track-api-calls-node-js-piwik/ and https://expressjs.com/en/guide/using-middleware.html
- [x] implement tracking for every URL call
  - use sensible action names, see https://developer.piwik.org/api-reference/tracking-api
  - custom variables to hold more information
- [x] add configuration
  - Piwik token as env variable
  - enable/disable tracking completely via env variable

## Questions

1. Which badge type is requested how often?
1. What are the most (Top 10, Top 20, Top 100) requested DOIs of publications?
1. Which research websites are used how often? (via `referer` header)
1. What are the shares of "n/a" - badges? (for each badge type)
1. Which data-backend/"service" ist used how often (only if we have a badge where the same information is queried from different sources) ?
1. How many requests do not come from the o2r-extender?
1. What are the shares for extended (/ svg / png) badges?
1. Which extender version are users using? What is the version distribution?

**Comment by nuest** [comment]
**Questions to answer with the data:**

[.. moved to first comment, integrated with @LukasLohoff ones]

**Comment by LukasLohoff** [comment]
Extension version and data-backend (service) are not available right now. Options:

- We could add the extension version to the o2r-extender by putting it in a (custom) HTTP header. Or is there a better way?
- The `/service/` isn't part of the URL any longer and I can't think of a way to get it, because the badger is supposed to decide which service to use. And the tracking happens before the badge is generated and sent.

**Comment by nuest** [comment]
:+1: for the custom HTTP header for extender.

Re. `/service`: Couldn't you add another event after the badge is generated? Or move the whole event generation to that point in the process?

I integrated our two lists, with priorities, into the first comment.

**Comment by LukasLohoff** [comment]
The extender version via custom header is working now.

And doing the tracking after the badge is generated is also working with `res.on('finish' ...)`. Putting the `/service/` back into the request is a bit more work though.

**Comment by nuest** [comment]
No, `/service/` should _not_ be part of the request URL.

I mean that the actually used third party service should be part of the tracking event.

**Comment by nuest** [comment]
@LukasLohoff This seems like it's done, please open the PR.
