### ISSUE TITLE
Add left-click action to extension button

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-badger#3]
When a user left-clicks on the icon in Chrome, nothing happens.

Why not open the menu, just as with a right click?
Or show the number of retrieved badges for the current page?

Other ideas what could be shown welcome.

**Comment by LukasLohoff** [comment]
Belongs to the o2r-extender, I created a new issue there. I think you can't move issues, right?

See https://github.com/o2r-project/o2r-extender/issues/4

**Comment by nuest** [comment]
Sorry! Thanks for moving the issue, my bad.
