### ISSUE TITLE
Make timeout configurable per service

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-badger#8]
Right now the timeout is quite high, so the requests to the badger are open for quite some time, allowing a lot of time for the third party services in the backend to reply. This could be a good thing, but puts additional load on the badger (keeping all the connections open) and also is not an optimal user experience.

Therefore it should be possible to configure a timeout for each service (e.g. doaj, o2r) that is queried for badge information in the background, and return the request to the user of the badger API quicker.

**Comment by LukasLohoff** [comment]
closed with #9
